require 'nokogiri'
require 'open-uri'
# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
puts "Clean base ..."

Pin.destroy_all
Region.destroy_all
Categorie.destroy_all
Post.destroy_all


puts "Create regions ..."

hokkaido = Region.create(name: "Hokkaido", description: "Hokkaido is the northernmost of Japan’s main islands, known for its volcanoes, natural hot springs (onsen) and ski areas. Rugged Daisetsuzan National Park is home to steaming, volcanic Mount Asahi. Shikotsu-Tōya National Park contains caldera lakes, geothermal springs and a Mount Fuji look-alike, Mount Yōtei. Popular ski resorts include Rusutsu, Furano and Niseko.")
tohoku = Region.create(name: "Tohoku", description: "Tohoku is a region of Japan’s Honshu Island, home to scenic lakes, forests, mountains and temples. In the remote Dewa Sanzan mountains, the Three Sacred Mountains of Dewa are pilgrimage sites with ancient Shinto shrines. The city of Sendai is known for its castle and the Osaki Hachimangu Shinto shrine. The town of Yamagata is home to the Yamadera temple complex, with its hilltop pagoda.")
kanto = Region.create(name: "Kanto", description: "Kanto is a region on the Japanese island of Honshu that includes the Greater Tokyo Area and its prefectures. In Tokyo, the capital, skyscrapers, shopping and pop culture meet traditional temples, shrines and cherry blossoms. Mount Fuji, a symmetrical volcano, lies southwest of Tokyo, and Hakone has hot springs and a scenic mountain lake. Izu Peninsula is known for beaches, diving and onsen resorts.")
chubu = Region.create(name: "Chubu", description: "Chubu is a region in central Japan, home to the country’s iconic Mount Fuji. The mountain’s climbing routes include the Yoshida Trail, which starts at the Fuji Subaru Line 5th Station. The Fuji Five Lakes area encompasses lakes and hot springs. In the Nagano prefecture, the city of Matsumoto is known for Matsumoto Castle, a 16th-century stronghold nicknamed “Crow Castle” for its black exterior.")
kansai = Region.create(name: "Kansai", description: "Kansai is a region on the Japanese island of Honshu. In its capital, Kyoto, the sprawling Nijo Castle was built in 1603, and the ornate gold pavilion of Kinkakuji dates to 1397. Kyoto is also home to the serene, centuries-old Zen gardens of Ryoanji temple and the ancient Buddhist complex of Nanzenji temple. Nearby is the city of Nara, Japan’s 8th-century capital, with the famous Todaiji temple.")
chugoku = Region.create(name: "Chugoku", description: "Chugoku is a region on the Inland Sea coast of western Honshu, Japan’s main island. It’s known for cities like Hiroshima, a modern metropolis on the site of the atomic bomb attack in 1945. The city of Okayama is home to the Korakuen Garden, with its traditional landscaping and teahouses. The region’s islands include the mountainous, pine-covered Shodo Island and the sandy beaches of Miyajima.")
shikoku = Region.create(name: "Shikoku", description: "Shikoku is the smallest of Japan’s four main islands. It’s rural, mountainous and heavily forested, with a craggy, 1,982m peak, Mount Ishizuchi, at its heart. Just off Shikoku’s eastern coast, Naruto Strait is famous for whirlpools. The prefecture of Ehime is home to the city of Matsuyama, with its hilltop Matsuyama Castle and Dogo Onsen, one of Japan’s oldest hot-spring resorts.")
kyushu = Region.create(name: "Kyushu", description: "Kyushu, the southwesternmost of Japan’s main islands, has a mostly subtropical climate. It’s known for its active volcanoes, beaches and natural hot springs such as those at Beppu. Its city of Fukuoka is home to museums, mega-malls and Kushida-jinja, an 8th-century Shinto shrine. The city of Nagasaki's 1945 devastation by an atomic bomb is commemorated at the Nagasaki Peace Park and Atomic Bomb Museum.")
okinawa = Region.create(name: "Okinawa", description: "Okinawa is a Japanese prefecture comprising more than 150 islands in the East China Sea between Taiwan and Japan's mainland. It's known for its tropical climate, broad beaches and coral reefs, as well as World War II sites. On the largest island (also named Okinawa) is Okinawa Prefectural Peace Memorial Museum, commemorating a massive 1945 Allied invasion, and Churaumi Aquarium, home to whale sharks and manta rays.")

puts "Create categories ..."

food = Categorie.create(name: "Food", description: "Japanese cuisine (和食, washoku) offers an abundance of gastronomical delights with a boundless variety of regional and seasonal dishes. Restaurants in Japan range from mobile food stands to centuries old ryotei, atmospheric drinking places, seasonally erected terraces over rivers, cheap chain shops and unique theme restaurants about ninja and robots. Many restaurants are specialized in a single type of dish, while others offer a variety of dishes.")
pop_culture = Categorie.create(name: "Pop-Culture", description: "Modern day manga (漫画) can be defined as comics corresponding to a Japanese style, which originated during the mid-1900s. The popularity of manga in Japan has since ballooned. Today, there is a huge domestic industry for manga, and increasingly so internationally. In Japan, people of both genders and all ages read manga.")
tradition = Categorie.create(name: "Tradition", description: "Japanese culture is rich and diverse, dating back to 10,000BC when the Jomon people first settled in Japan. It is widely known for its traditional arts as well as its contemporary pop culture. Today, Japan is a constitutional monarchy, and is home to a population of 127 million people.")
craftmanship = Categorie.create(name: "Craftmanship", description: "Japanese craftsmanship is an age-old tradition that has been passed down from generation to generation. It is a tradition that has been perfected over the years, and is still being perfected today. Japanese craftsmanship is a tradition that has been passed down from generation to generation. It is a tradition that has been perfected over the years, and is still being perfected today.")
nature = Categorie.create(name: "Nature", description: "Japan is a country of islands, so the sea is never far away. The country's coastline stretches for more than 18,000 miles, and there are thousands of beaches, both on the mainland and on the many islands. Japan is also home to many mountains, some of which are volcanoes. The country is also home to many rivers and lakes.")

puts "Create posts ..."

jingisukan = Post.create(content: "Jingisukan (ジンギスカン, \"Genghis Khan\") is a Japanese grilled mutton dish prepared on a convex metal skillet or other grill. The dish is particularly popular on the northern island of Hokkaido, in China and in Thailand.", multimedia: "/assets/images/jingisukan.jpg")
senbei_jiru = Post.create(content: "Senbei-jiru (煎餅汁) is a Japanese soup made from rice crackers (senbei) and vegetables. It is a specialty of the city of Akita, Akita Prefecture, Japan.", multimedia: "/assets/images/senbei_jiru.jpg")
kiritanpo = Post.create(content: "Kiritanpo (きりたんぽ) is a type of rice-based dish in Akita Prefecture, Japan. It is made from freshly cooked rice, which is mashed, formed into cylinders around a skewer, and then grilled.", multimedia: "/assets/images/kiritanpo.jpg")
wanko_soba = Post.create(content: "Wanko soba (わんこそば) is a type of Japanese noodle dish where the diner is given a bowl of soba noodles and is encouraged to eat as many bowls as they can. The name comes from the Japanese word for dog, wan (わん), and the word for small bowl, ko (こ).", multimedia: "/assets/images/wanko_soba.jpg")
imoni = Post.create(content: "Imoni (芋煮) is a Japanese taro and meat (usually beef) stew. It is a regional dish of the Tōhoku region, particularly in Yamagata Prefecture and Akita Prefecture.", multimedia: "/assets/images/imoni.jpg")

akihabara = Post.create(content: "Akihabara (秋葉原), also called Akiba after a former local shrine, is a district in central Tokyo that is famous for its many electronics shops. In more recent years, Akihabara has gained recognition as the center of Japan's otaku (diehard fan) culture, and many shops and establishments devoted to anime and manga are now dispersed among the electronic stores in the district.", multimedia: "/assets/images/akihabara.jpg")
den_den_town = Post.create(content: "Den Den Town (でんでんタウン), also known as Nipponbashi (日本橋), is a shopping district in Osaka famous for its wide selection of electronic, anime, and otaku goods. It is comparable to Akihabara, except that it is smaller in size and less well known outside of Kansai.", multimedia: "/assets/images/den_den_town.jpg")
osaka_universal_studio = Post.create(content: "Universal Studios Japan (ユニバーサル・スタジオ・ジャパン, Yunibāsaru Sutajio Japan), located in Osaka, is one of six Universal Studios theme parks, owned and operated by USJ Co., Ltd., which is wholly owned by NBCUniversal (as of 2017). The park is similar to the Universal Orlando Resort since it also contains selected attractions from Universal Orlando Resort and Universal Studios Hollywood.", multimedia: "/assets/images/osaka_universal_studio.jpg")
ghibli_museum = Post.create(content: "The Ghibli Museum (三鷹の森ジブリ美術館, Mitaka no Mori Jiburi Bijutsukan, Mitaka Forest Ghibli Museum) is a museum showcasing the work of the Japanese animation studio Studio Ghibli. It is located in Inokashira Park in Mitaka, a western city of Tokyo, Japan. The museum combines features of a children's museum, technology museum, and a fine arts museum, and is dedicated to the art and technique of animation.", multimedia: "/assets/images/ghibli_museum.jpg")
tokyo_disneyland = Post.create(content: "Tokyo Disneyland (東京ディズニーランド, Tōkyō Dizunīrando) is a 115-acre (47 ha) theme park at the Tokyo Disney Resort in Urayasu, Chiba Prefecture, Japan, near Tokyo. Its main gate is directly adjacent to both Maihama Station and Tokyo Disneyland Station. It was the first Disney park to be built outside the United States, and it opened on 15 April 1983. The park was constructed by Walt Disney Imagineering in the same style as Disneyland in California and Magic Kingdom in Florida. It is owned by The Oriental Land Company, which licenses the theme from The Walt Disney Company. Tokyo Disneyland and its companion park, Tokyo DisneySea, are the only Disney parks not wholly or partly owned by the Walt Disney Company (however, Disney has creative control).", multimedia: "/assets/images/tokyo_disneyland.jpg")

kinkakuji = Post.create(content: "Kinkaku-ji (金閣寺, literally \"Temple of the Golden Pavilion\"), officially named Rokuon-ji (鹿苑寺, literally \"Deer Garden Temple\"), is a Zen Buddhist temple in Kyoto, Japan. It is one of the most popular buildings in Japan, attracting a large number of visitors annually. It is designated as a National Special Historic Site, a National Special Landscape and is one of 17 locations making up the Historic Monuments of Ancient Kyoto which are World Heritage Sites.", multimedia: "/assets/images/kinkakuji.jpg")
izumo_taisha = Post.create(content: "Izumo-taisha (出雲大社, Izumo Grand Shrine), officially Izumo Ōyashiro, is one of the most ancient and important Shinto shrines in Japan. No record gives the date of establishment. Located in Izumo, Shimane Prefecture, it is home to two major festivals. It is dedicated to the god Ōkuninushi (大国主大神, Ōkuninushi no Ōkami), famous as the Shinto deity of marriage and to Kotoamatsukami (別天津神, Kotoamatsukami no Kami) who is the highest deity in the Shinto pantheon.", multimedia: "/assets/images/izumo_taisha.jpg")
byodo_in = Post.create(content: "Byōdō-in (平等院) is a Buddhist temple in the city of Uji in Kyoto Prefecture, Japan, built in late Heian period. It is jointly a temple of the Jōdo-shū (Pure Land) and Tendai-shū sects. This temple was originally built in 998 in the Heian period as a rural villa of high-ranking courtier Minamoto no Shigenobu, Minister of the Left. The estate was purchased in 1052 by Fujiwara no Yorimichi, regent to Emperor Go-Reizei, who began converting the villa into a temple. In 1053, a main hall, lecture hall and pagoda were added to the temple complex, and it was inaugurated as Jōdo-shū's head temple, Seigan-ji (清願寺, \"Temple of Purity and Vows\").", multimedia: "/assets/images/byodo_in.jpg")
yama_dera = Post.create(content: "Yamadera (山寺), officially Risshaku-ji (立石寺), is a Buddhist temple located in Yamagata, Yamagata Prefecture, Japan. It is the most famous temple in the Tōhoku region and is ranked 42nd of the 88 temples in the Shikoku Pilgrimage. The temple, which is located within the city limits of Yamagata, stands on the slopes of Mount Hōshū, and was founded in 860 by Jikaku Daishi (Ennin), a monk of the Tendai sect of Buddhism.", multimedia: "/assets/images/yama_dera.jpg")
todai_ji = Post.create(content: "Tōdai-ji (東大寺, Eastern Great Temple) is a Buddhist temple complex that was once one of the powerful Seven Great Temples, located in the city of Nara, Japan. Its Great Buddha Hall (大仏殿, Daibutsuden) houses the world's largest bronze statue of the Buddha Vairocana, known in Japanese simply as Daibutsu (大仏). The temple also serves as the Japanese headquarters of the Kegon school of Buddhism. The temple is a listed UNESCO World Heritage Site as one of the \"Historic Monuments of Ancient Nara\", together with seven other sites including temples, shrines and places in the city of Nara. Sika deer, regarded as messengers of the gods in the Shinto religion, roam the grounds freely.", multimedia: "/assets/images/todai_ji.jpg")

sakai_knives = Post.create(content: "Sakai knives (堺包丁, Sakai hōchō) are knives made in Sakai, Japan. The city of Sakai is one of the many cities in Japan that is famous for its knives. Sakai knives are known for their quality and are often used by professionals.", multimedia: "/assets/images/sakai_knives.jpg")
kumano_brushes = Post.create(content: "Kumano brushes (熊野筆, Kumano fude) are brushes made in Kumano, Hiroshima Prefecture, Japan. The city of Kumano is one of the many cities in Japan that is famous for its brushes. Kumano brushes are known for their quality and are often used by professionals.", multimedia: "/assets/images/kumano_brushes.jpg")
kutani_porcelain = Post.create(content: "Kutani ware (九谷焼, Kutani-yaki) is a style of Japanese porcelain traditionally supposed to be from Kutani, now a part of Kaga, Ishikawa, in the former Kaga Province. It is divided into two phases: Ko-Kutani (old Kutani), from the 17th and early 18th centuries, and Saikō-Kutani from the revived production in the 19th century. The more prestigious Ko-Kutani wares are recognised by scholars to be a complex and highly stylised and technically advanced group of porcelains, and represent the pinnacle of Japanese porcelain making. The porcelain style is known for multiple colors—such as greens, blues, yellows, purples, and reds—and bold designs covering most of the surface of each piece.", multimedia: "/assets/images/kutani_porcelain.jpg")
washi = Post.create(content: "Washi (和紙) is traditional Japanese paper. The word \"washi\" comes from wa meaning 'Japanese' and shi meaning 'paper'. The term is used to describe paper that uses local fiber, processed by hand and made in the traditional manner. Washi is made using fibers from the inner bark of the gampi tree, the mitsumata shrub (Edgeworthia papyrifera), or the paper mulberry (kōzo) bush. As a method, washi is registered as a UNESCO intangible cultural heritage.", multimedia: "/assets/images/washi.jpg")
katana = Post.create(content: "The katana (刀 or かたな) is a type of Japanese sword (日本刀, nihontō), also commonly referred to as a \"samurai sword\". The term katana may be applied to the standard size moderately curved Japanese sword with a blade length of greater than 60 cm (23.6 inches).", multimedia: "/assets/images/katana.jpg")

tenryuji = Post.create(content: "Tenryū-ji (天龍寺, Temple of the Celestial Dragon) is the head temple of the Tenryū branch of Rinzai Zen Buddhism, located in Susukinobaba-chō, Ukyō Ward, Kyoto, Japan. The temple was founded by Ashikaga Takauji in 1339, primarily to venerate Gautama Buddha, and its first chief priest was Musō Soseki. Construction was completed in 1345. The temple's buildings were repeatedly destroyed over the centuries, most recently in 1864, and their current incarnation dates from 1900.", multimedia: "/assets/images/tenryuji.jpg")
ritsurin_koen = Post.create(content: "Ritsurin Garden (栗林公園, Ritsurin Kōen) is one of the most famous historical gardens in Japan. The garden is situated in the city of Takamatsu and is considered one of its main attractions. It is designated as a Special Place of Scenic Beauty of Japan.", multimedia: "/assets/images/ritsurin_koen.jpg")
korakuen = Post.create(content: "Kōraku-en (後楽園) is a Japanese garden located in Okayama, Okayama Prefecture. It is one of the Three Great Gardens of Japan, along with Kenroku-en and Kairaku-en. Korakuen was built in 1700 by Ikeda Tsunamasa, lord of Okayama.", multimedia: "/assets/images/korakuen.jpg")
ryoanji = Post.create(content: "Ryōan-ji (竜安寺, The Temple of the Dragon at Peace) is a Zen temple located in northwest Kyoto, Japan. It belongs to the Myōshin-ji school of the Rinzai branch of Zen Buddhism. The Ryōan-ji garden is considered one of the finest surviving examples of kare-sansui (枯山水), a refined type of Japanese Zen temple garden design generally featuring distinctive larger rock formations arranged amidst a sweep of smooth pebbles arranged in immaculate linear patterns, designed to facilitate meditation.", multimedia: "/assets/images/ryoanji.jpg")
kenrokuen = Post.create(content: "Kenroku-en (兼六園, Six Attributes Garden), located in Kanazawa, Ishikawa, Japan, is an old private garden. Along with Kairaku-en and Koraku-en, Kenroku-en is one of the Three Great Gardens of Japan. The garden is open year-round and charges an admission fee.", multimedia: "/assets/images/kenrokuen.jpg")

puts "Create pins ..."

jingisukan_pin = Pin.create!(name: "Jingisukan", description: "Jingisukan (ジンギスカン, \"Genghis Khan\") is a Japanese grilled mutton dish prepared on a convex metal skillet or other grill. The dish is particularly popular on the northern island of Hokkaido, in China and in Thailand.", latitude: 43.1906806, longitude: 140.9946021, categorie: food, region: hokkaido, post: jingisukan)
senbei_jiru_pin = Pin.create!(name: "Senbei-jiru", description: "Senbei-jiru (煎餅汁) is a Japanese soup made from rice crackers (senbei) and vegetables. It is a specialty of the city of Akita, Akita Prefecture, Japan.", latitude: 39.717538941852695, longitude: 140.10207265708942, categorie: food, region: tohoku, post: senbei_jiru)
kiritanpo_pin = Pin.create!(name: "Kiritanpo", description: "Kiritanpo (きりたんぽ) is a type of rice-based dish in Akita Prefecture, Japan. It is made from freshly cooked rice, which is mashed, formed into cylinders around a skewer, and then grilled.", latitude: 39.6898802, longitude: 140.342608, categorie: food, region: tohoku, post: kiritanpo)
wanko_soba_pin = Pin.create!(name: "Wanko soba", description: "Wanko soba (わんこそば) is a type of Japanese noodle dish where the diner is given a bowl of soba noodles and is encouraged to eat as many bowls as they can. The name comes from the Japanese word for dog, wan (わん), and the word for small bowl, ko (こ).", latitude: 39.7021331, longitude: 141.1545397, categorie: food, region: tohoku, post: wanko_soba)
imoni_pin = Pin.create!(name: "Imoni", description: "Imoni (芋煮) is a Japanese taro and meat (usually beef) stew. It is a regional dish of the Tōhoku region, particularly in Yamagata Prefecture and Akita Prefecture.", latitude: 38.4746705, longitude: 140.083237, categorie: food, region: tohoku, post: imoni)

akihabara_pin = Pin.create!(name: "Akihabara", description: "Akihabara (秋葉原), also called Akiba after a former local shrine, is a district in central Tokyo that is famous for its many electronics shops. In more recent years, Akihabara has gained recognition as the center of Japan's otaku (diehard fan) culture, and many shops and establishments devoted to anime and manga are now dispersed among the electronic stores in the district.", latitude: 35.7023, longitude: 139.7745, categorie: pop_culture, region: kanto, post: akihabara)
den_den_town_pin = Pin.create!(name: "Den Den Town", description: "Den Den Town (でんでんタウン), also known as Nipponbashi (日本橋), is a shopping district in Osaka famous for its wide selection of electronic, anime, and otaku goods. It is comparable to Akihabara, except that it is smaller in size and less well known outside of Kansai.", latitude: 34.6675, longitude: 135.5019, categorie: pop_culture, region: kansai, post: den_den_town)
osaka_universal_studio_pin = Pin.create!(name: "Osaka Universal Studio", description: "Universal Studios Japan (ユニバーサル・スタジオ・ジャパン, Yunibāsaru Sutajio Japan), located in Osaka, is one of six Universal Studios theme parks, owned and operated by USJ Co., Ltd., which is wholly owned by NBCUniversal (as of 2017). The park is similar to the Universal Orlando Resort since it also contains selected attractions from Universal Orlando Resort and Universal Studios Hollywood.", latitude: 34.6654, longitude: 135.4323, categorie: pop_culture, region: kansai, post: osaka_universal_studio)
ghibli_museum_pin = Pin.create!(name: "Ghibli Museum", description: "The Ghibli Museum (三鷹の森ジブリ美術館, Mitaka no Mori Jiburi Bijutsukan, Mitaka Forest Ghibli Museum) is a museum showcasing the work of the Japanese animation studio Studio Ghibli. It is located in Inokashira Park in Mitaka, a western city of Tokyo, Japan. The museum combines features of a children's museum, technology museum, and a fine arts museum, and is dedicated to the art and technique of animation.", latitude: 35.6962, longitude: 139.5703, categorie: pop_culture, region: kanto, post: ghibli_museum)
tokyo_disneyland_pin = Pin.create!(name: "Tokyo Disneyland", description: "Tokyo Disneyland (東京ディズニーランド, Tōkyō Dizunīrando) is a 115-acre (47 ha) theme park at the Tokyo Disney Resort in Urayasu, Chiba Prefecture, Japan, near Tokyo. Its main gate is directly adjacent to both Maihama Station and Tokyo Disneyland Station. It was the first Disney park to be built outside the United States, and it opened on 15 April 1983. The park was constructed by Walt Disney Imagineering in the same style as Disneyland in California and Magic Kingdom in Florida. It is owned by The Oriental Land Company, which licenses the theme from The Walt Disney Company. Tokyo Disneyland and its companion park, Tokyo DisneySea, are the only Disney parks not wholly or partly owned by the Walt Disney Company (however, Disney has creative control).", latitude: 35.6329, longitude: 139.8804, categorie: pop_culture, region: kanto, post: tokyo_disneyland)

kinkakuji_pin = Pin.create!(name: "Kinkaku-ji", description: "Kinkaku-ji (金閣寺, literally \"Temple of the Golden Pavilion\"), officially named Rokuon-ji (鹿苑寺, literally \"Deer Garden Temple\"), is a Zen Buddhist temple in Kyoto, Japan.", latitude: 35.0394, longitude: 135.7294, categorie: tradition, region: kansai, post: kinkakuji)
izumo_taisha_pin = Pin.create!(name: "Izumo-taisha", description: "Izumo-taisha (出雲大社, Izumo Grand Shrine), officially Izumo Ōyashiro, is one of the most ancient and important Shinto shrines in Japan. No record gives the date of establishment. Located in Izumo, Shimane Prefecture, it is home to two major festivals. It is dedicated to the god Ōkuninushi (大国主大神, Ōkuninushi no Ōkami), famous as the Shinto deity of marriage and to Kotoamatsukami (別天津神, Kotoamatsukami no Kami) who is the highest deity in the Shinto pantheon.", latitude: 35.4073, longitude: 132.6958, categorie: tradition, region: chugoku, post: izumo_taisha)
byodo_in_pin = Pin.create!(name: "Byōdō-in", description: "Byōdō-in (平等院) is a Buddhist temple in the city of Uji in Kyoto Prefecture, Japan, built in late Heian period. It is jointly a temple of the Jōdo-shū (Pure Land) and Tendai-shū sects. This temple was originally built in 998 in the Heian period as a rural villa of high-ranking courtier Minamoto no Shigenobu, Minister of the Left. The estate was purchased in 1052 by Fujiwara no Yorimichi, regent to Emperor Go-Reizei, who began converting the villa into a temple. In 1053, a main hall, lecture hall and pagoda were added to the temple complex, and it was inaugurated as Jōdo-shū's head temple, Seigan-ji (清願寺, \"Temple of Purity and Vows\").", latitude: 34.8894, longitude: 135.8079, categorie: tradition, region: kansai, post: byodo_in)
yama_dera_pin = Pin.create!(name: "Yamadera", description: "Yamadera (山寺), officially Risshaku-ji (立石寺), is a Buddhist temple located in Yamagata, Yamagata Prefecture, Japan. It is the most famous temple in the Tōhoku region and is ranked 42nd of the 88 temples in the Shikoku Pilgrimage. The temple, which is located within the city limits of Yamagata, stands on the slopes of Mount Hōshū, and was founded in 860 by Jikaku Daishi (Ennin), a monk of the Tendai sect of Buddhism.", latitude: 38.6278, longitude: 140.2281, categorie: tradition, region: tohoku, post: yama_dera)
todai_ji_pin = Pin.create!(name: "Tōdai-ji", description: "Tōdai-ji (東大寺, Eastern Great Temple) is a Buddhist temple complex that was once one of the powerful Seven Great Temples, located in the city of Nara, Japan. Its Great Buddha Hall (大仏殿, Daibutsuden) houses the world's largest bronze statue of the Buddha Vairocana, known in Japanese simply as Daibutsu (大仏). The temple also serves as the Japanese headquarters of the Kegon school of Buddhism. The temple is a listed UNESCO World Heritage Site as one of the \"Historic Monuments of Ancient Nara\", together with seven other sites including temples, shrines and places in the city of Nara. Sika deer, regarded as messengers of the gods in the Shinto religion, roam the grounds freely.", latitude: 34.6892, longitude: 135.8392, categorie: tradition, region: kansai, post: todai_ji)

sakai_knives_pin = Pin.create!(name: "Sakai knives", description: "Sakai knives (堺包丁, Sakai hōchō) are knives made in Sakai, Japan. The city of Sakai is one of the many cities in Japan that is famous for its knives. Sakai knives are known for their quality and are often used by professionals.", latitude: 34.5732, longitude: 135.483, categorie: craftmanship, region: kansai, post: sakai_knives)
kumano_brushes_pin = Pin.create!(name: "Kumano brushes", description: "Kumano brushes (熊野筆, Kumano fude) are brushes made in Kumano, Hiroshima Prefecture, Japan. The city of Kumano is one of the many cities in Japan that is famous for its brushes. Kumano brushes are known for their quality and are often used by professionals.", latitude: 34.33619818197904, longitude: 132.58428120605652, categorie: craftmanship, region: chugoku, post: kumano_brushes)
kutani_porcelain_pin = Pin.create!(name: "Kutani porcelain", description: "Kutani ware (九谷焼, Kutani-yaki) is a style of Japanese porcelain traditionally supposed to be from Kutani, now a part of Kaga, Ishikawa, in the former Kaga Province. It is divided into two phases: Ko-Kutani (old Kutani), from the 17th and early 18th centuries, and Saikō-Kutani from the revived production in the 19th century. The more prestigious Ko-Kutani wares are recognised by scholars to be a complex and highly stylised and technically advanced group of porcelains, and represent the pinnacle of Japanese porcelain making. The porcelain style is known for multiple colors—such as greens, blues, yellows, purples, and reds—and bold designs covering most of the surface of each piece.", latitude: 36.4330682, longitude: 136.5252243, categorie: craftmanship, region: chubu, post: kutani_porcelain)
washi_pin = Pin.create!(name: "Washi", description: "Washi (和紙) is traditional Japanese paper. The word \"washi\" comes from wa meaning 'Japanese' and shi meaning 'paper'. The term is used to describe paper that uses local fiber, processed by hand and made in the traditional manner. Washi is made using fibers from the inner bark of the gampi tree, the mitsumata shrub (Edgeworthia papyrifera), or the paper mulberry (kōzo) bush. As a method, washi is registered as a UNESCO intangible cultural heritage.", latitude: 35.9034571, longitude: 136.1689317, categorie: craftmanship, region: chubu, post: washi)
katana_pin = Pin.create!(name: "Katana", description: "The katana (刀 or かたな) is a type of Japanese sword (日本刀, nihontō), also commonly referred to as a \"samurai sword\".", latitude: 35.4958031, longitude: 136.9181482, categorie: craftmanship, region: chubu, post: katana)

tenryuji_pin = Pin.create!(name: "Tenryū-ji", description: "Tenryū-ji (天龍寺, Temple of the Celestial Dragon) is the head temple of the Tenryū branch of Rinzai Zen Buddhism, located in Susukinobaba-chō, Ukyō Ward, Kyoto, Japan. The temple was founded by Ashikaga Takauji in 1339, primarily to venerate Gautama Buddha, and its first chief priest was Musō Soseki. Construction was completed in 1345. The temple's buildings were repeatedly destroyed over the centuries, most recently in 1864, and their current incarnation dates from 1900.", latitude: 35.0153, longitude: 135.6739, categorie: nature, region: kansai, post: tenryuji)
ritsurin_koen_pin = Pin.create!(name: "Ritsurin Garden", description: "Ritsurin Garden (栗林公園, Ritsurin Kōen) is one of the most famous historical gardens in Japan. The garden is situated in the city of Takamatsu and is considered one of its main attractions. It is designated as a Special Place of Scenic Beauty of Japan.", latitude: 34.3422, longitude: 134.0444, categorie: nature, region: shikoku, post: ritsurin_koen)
korakuen_pin = Pin.create!(name: "Kōraku-en", description: "Kōraku-en (後楽園) is a Japanese garden located in Okayama, Okayama Prefecture. It is one of the Three Great Gardens of Japan, along with Kenroku-en and Kairaku-en. Korakuen was built in 1700 by Ikeda Tsunamasa, lord of Okayama.", latitude: 34.6667, longitude: 133.9333, categorie: nature, region: chugoku, post: korakuen)
ryoanji_pin = Pin.create!(name: "Ryōan-ji", description: "Ryōan-ji (竜安寺, The Temple of the Dragon at Peace) is a Zen temple located in northwest Kyoto, Japan. It belongs to the Myōshin-ji school of the Rinzai branch of Zen Buddhism. The Ryōan-ji garden is considered one of the finest surviving examples of kare-sansui (枯山水), a refined type of Japanese Zen temple garden design generally featuring distinctive larger rock formations arranged amidst a sweep of smooth pebbles arranged in immaculate linear patterns, designed to facilitate meditation.", latitude: 35.0325, longitude: 135.7219, categorie: nature, region: kansai, post: ryoanji)
kenrokuen_pin = Pin.create!(name: "Kenroku-en", description: "Kenroku-en (兼六園, Six Attributes Garden), located in Kanazawa, Ishikawa, Japan, is an old private garden.", latitude: 36.5613, longitude: 136.6562, categorie: nature, region: chubu, post: kenrokuen)

puts "Finished seeding!"
